name: Matrix Echo Example

on: [push, pull_request]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate matrix
      id: generate
      run: |
        python generate-matrix.py > matrix.json
        echo "::set-output name=matrix::$(cat matrix.json)"

  echo-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vars: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo variables
      run: |
        for var in ${{ toJson(matrix.vars) }}; do
          echo "$var is ${{ matrix.vars[var] }}"
        done
